CREATE TABLE IF NOT EXISTS qrcodes (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid            CHAR(36)     NOT NULL UNIQUE,
    user_id         BIGINT UNSIGNED NOT NULL,
    organization_id BIGINT UNSIGNED NULL,
    type            ENUM(
                        'url','text','email','phone','sms','whatsapp',
                        'wifi','vcard','geo','event','bitcoin','pix'
                    ) NOT NULL DEFAULT 'url',
    content         TEXT         NOT NULL,
    label           VARCHAR(120),
    fg_color        CHAR(7)      NOT NULL DEFAULT '#000000',
    bg_color        CHAR(7)      NOT NULL DEFAULT '#FFFFFF',
    transparent     TINYINT(1)   NOT NULL DEFAULT 0,
    ecc_level       ENUM('L','M','Q','H') NOT NULL DEFAULT 'M',
    size            SMALLINT UNSIGNED NOT NULL DEFAULT 512,
    logo_path       VARCHAR(255)    NULL COMMENT 'logo do cliente (upload)',
    logo_size       TINYINT UNSIGNED NOT NULL DEFAULT 20,
    has_qr_logo     TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'QR-Logo renderizado',
    legibility_index TINYINT UNSIGNED NULL COMMENT 'Indice PRISMA 0-100',
    file_png        VARCHAR(255),
    file_svg        VARCHAR(255),
    file_logo_png   VARCHAR(255)    NULL COMMENT 'QR-Logo final',
    short_code      VARCHAR(10)  UNIQUE,
    short_url       VARCHAR(512),
    scan_count      INT UNSIGNED NOT NULL DEFAULT 0,
    render_status   ENUM('pending','processing','done','failed') NOT NULL DEFAULT 'done',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    INDEX idx_user    (user_id),
    INDEX idx_type    (type),
    INDEX idx_short   (short_code),
    INDEX idx_status  (render_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
