[program:prisma-qrlogo-worker]
command=php /var/www/prisma/workers/queue-worker.php qrlogo
directory=/var/www/prisma
user=www-data
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=3
startsecs=1
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/prisma-qrlogo.log
stderr_logfile=/var/log/supervisor/prisma-qrlogo-err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stopasgroup=true
killasgroup=true

[program:prisma-default-worker]
command=php /var/www/prisma/workers/queue-worker.php default
directory=/var/www/prisma
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=3
startsecs=1
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/prisma-worker.log
stderr_logfile=/var/log/supervisor/prisma-worker-err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stopasgroup=true
killasgroup=true
